# Generated by Django 3.0.1 on 2019-12-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='UrlShortener',
        ),
    ]
