# Generated by Django 3.0.1 on 2019-12-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0002_auto_20191224_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='storedURL',
            field=models.URLField(max_length=250),
        ),
    ]
